# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ata_piix" "usb_storage" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f67b21ce-15c8-4008-bd08-01763f5cd4be";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/115d6657-bb74-4d6b-bd04-7557a83ebd52"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
}
